sonar.projectKey=myproject
sonar.projectName=My Project
sonar.projectVersion=1.0

sonar.sources=src
sonar.tests=tests

sonar.sourceEncoding=UTF-8

sonar.host.url=http://localhost:9000

sonar.login=YOUR_TOKEN

giude == github_pat_11BK3WAMY0rREcJQtsju8B  _iJZpOfwuyg0uUFWDdie7JO4DVRocMuNUEmaTPvL50vqWL6KSNK6dSHP2vQn
ese == github_pat_11BK3WAMY0mBAV8K04MSV5  _o8p4RGBBiWomYiJSDR88hgxwQy1Bbi5bZ3D9sgngmo2EOWGWVEJcnadUmpX